---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  type: ClusterIP
  selector:
    quarks.cloudfoundry.org/instance-group-name: nats
    quarks.cloudfoundry.org/deployment-name: nats-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4222
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-manifest
    update:
      canary_watch_time: "120000000"
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    instance_groups:
    - name: nats
      instances: 2
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
          quarks:
            ports:
            - name: "nats"
              protocol: "TCP"
              internal: 4222
            - name: "nats-routes"
              protocol: TCP
              internal: 4223
    variables:
    - name: nats_password
      type: password
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
