---
apiVersion: v1
kind: Secret
metadata:
  name: var-system-domain
type: Opaque
stringData:
  value: foo.com
---
apiVersion: v1
kind: Secret
metadata:
  name: my-nats-password
type: Opaque
stringData:
  password: deadbeef
---
apiVersion: v1
kind: Secret
metadata:
  name: my-ca
type: Opaque
stringData:
  certificate: "my-ca-cert-data"
  private_key: "my-ca-private-key"
  is_ca: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: my-cert
type: Opaque
stringData:
  certificate: "my-cert-data"
  private_key: "my-private-key-data"
  is_ca: "false"
  ca: "my-ca-cert-data"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-deployment
    releases:
    - name: nats
      version: "33"
      url: docker.io/cfcontainerization
      stemcell:
        os: SLE_15_SP1
        version: 26.1-7.0.0_374.gb8e8e6af
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((nats_password))
            domain: ((system_domain))
            ca_cert: ((nats_ca.certificate))
            ca_key: ((nats_ca.private_key))
            cert: ((nats_cert.certificate))
            key: ((nats_cert.private_key))
            cert_ca: ((nats_cert.ca))
    variables:
    - name: nats_password
      type: password
    - name: nats_ca
      type: certificate
      options:
        is_ca: true
        common_name: routerCA
    - name: nats_cert
      type: certificate
      options:
        ca: nats_ca
        common_name: routerSSL
        alternative_names:
        - "foo.bar"
        - "*.foo.bar"
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
  vars:
  - name: nats_password
    secret: my-nats-password
  - name: nats_ca
    secret: my-ca
  - name: nats_cert
    secret: my-cert
