---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-manifest
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: ((customed_password))
    variables:
    - name: nats_password
      type: password
    - name: customed_password
      type: password
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ops-foo
data:
  ops: |
    - type: replace
      path: /instance_groups/name=nats?/instances
      value: 2
---
apiVersion: v1
kind: Secret
metadata:
  name: nats-manifest.var-customed-password
type: Opaque
stringData:
  password: customed_password

---
apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    ref: nats-manifest
    type: configmap
  ops:
  - ref: ops-foo
    type: configmap
