---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-manifest
data:
  manifest: |
    ---
    name: nats-manifest
    releases:
    - name: nats
      version: "26"
      url: docker.io/cfcontainerization
      stemcell:
        os: opensuse-42.3
        version: 30.g9c91e77-30.80-7.0.0_257.gb97ced55
    addons:
    - name: bosh-dns-aliases
      jobs:
      - name: bosh-dns-aliases
        properties:
          aliases:
            - domain: _.myplaceholderalias.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: default
                  query: _
            - domain: nats.service.cf.internal
              targets:
                - deployment: cf
                  domain: bosh
                  instance_group: nats
                  network: default
                  query: "*"
    instance_groups:
    - name: nats
      instances: 1
      jobs:
      - name: nats
        release: nats
        properties:
          nats:
            user: admin
            password: "test"
          quarks:
            ports:
            - name: "nats"
              protocol: "TCP"
              internal: 4222
            - name: "nats-routes"
              protocol: TCP
              internal: 4223
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: nats-deployment
spec:
  manifest:
    name: nats-manifest
    type: configmap
