language: go

go:
  - '1.13.7'

cache:
  directories:
    - $GOPATH/pkg/mod

services:
  - docker

env:
  global:
    - GOPROXY="https://proxy.golang.org"
    - DOCKER_IMAGE_TAG=dev
    - CF_OPERATOR_WEBHOOK_SERVICE_HOST=172.17.0.1
    - OPERATOR_TEST_STORAGE_CLASS=local-path
  jobs:
    - KUBE=1.13.12
    - KUBE=1.15.6
    - KUBE=1.16.3

stages:
  - lint
  - unit
  - test

install:
  # Download ruby dev dependencies
  - gem install bosh-template
  # Download go dev dependencies
  - export PATH=$PATH:$GOPATH/bin
  - go install github.com/onsi/ginkgo/ginkgo
  # speed up build?
  - go mod vendor

before_script:
  # Download and install helm
  - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
  - chmod 700 get_helm.sh
  - sudo ./get_helm.sh
  # Download and install kubectl
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
  # Download and install KinD
  - curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/v0.6.0/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
  # Create a new Kubernetes cluster using KinD
  - kind create cluster --image kindest/node:v$KUBE --name kind$KUBE --wait 20s
  - kubectl version
  # Add local-path storage support
  - |
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
  - |
    kubectl patch storageclass standard --patch '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false", "storageclass.beta.kubernetes.io/is-default-class":"false"}}}'
  - |
    kubectl patch storageclass local-path --patch '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true", "storageclass.beta.kubernetes.io/is-default-class":"true"}}}'
script:
  - bin/build-image
  - kind load docker-image "cfcontainerization/cf-operator:dev" --name kind$KUBE
  - bin/test-integration
  - bin/test-integration storage
  - bin/test-integration util
  - bin/test-cli-e2e
  - bin/test-helm-e2e
  - bin/test-helm-e2e-storage

jobs:
  include:
    - stage: lint
      services: []
      before_script:
        - curl -LO https://github.com/dominikh/go-tools/releases/download/2019.2.3/staticcheck_linux_amd64.tar.gz
        - tar xfz staticcheck_linux_amd64.tar.gz --strip-component 1 -C $GOPATH/bin staticcheck/staticcheck
        - go get -u golang.org/x/lint/golint
      name: lint
      script:
        - bin/lint
        - bin/vet
        - bin/staticcheck
    - script: bin/test-unit
      name: unit
      # don't inherit
      services: []
      before_script: []
