apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extendedsecrets.fissile.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: fissile.cloudfoundry.org
  names:
    kind: ExtendedSecret
    listKind: ExtendedSecretList
    plural: extendedsecrets
    singular: extendedsecret
    shortNames:
        - esec
  scope: Namespaced
  version: v1alpha1
