{{- if .Values.customResources.enableInstallation }}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: extendedjobs.fissile.cloudfoundry.org
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: fissile.cloudfoundry.org
  names:
    kind: ExtendedJob
    listKind: ExtendedJobList
    plural: extendedjobs
    singular: extendedjob
    shortNames:
        - ejob
        - ejobs
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
  validation:
    # openAPIV3Schema is the schema for validating custom objects.
    openAPIV3Schema:
      properties:
        spec:
          required: [template]
          properties:
            output:
              type: object
              required: [namePrefix]
              properties:
                namePrefix:
                  type: string
                outputType:
                  type: string
                secretLabels:
                  type: object
                writeOnFailure:
                  type: boolean
            trigger:
              type: object
              required: [strategy]
              properties:
                strategy:
                  type: string
                  enum: ["manual", "once", "now", "done"]
                when:
                  type: string
                  enum: ["ready", "notready", "created", "deleted"]
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
                    matchExpressions:
                      type: array
                      items:
                        type: object
            template:
              type: object
            updateOnConfigChange:
              type: boolean
{{- end }}
