apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cf-operator
  template:
    metadata:
      labels:
        name: cf-operator
    spec:
      serviceAccountName: cf-operator
      containers:
        - name: cf-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - cf-operator
          imagePullPolicy: Always
          env:
            - name: CF_OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cf-operator"
            - name: CF_OPERATOR_WEBHOOK_HOST
              value: {{ .Release.Name }}-webhook
            - name: CF_OPERATOR_WEBHOOK_PORT
              value: "{{ .Values.operator.webhook.port }}"
