apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: boshdeployments.fissile.suse.com
spec:
  group: fissile.suse.com
  names:
    kind: BOSHDeployment
    listKind: BOSHDeploymentList
    plural: boshdeployments
    singular: boshdeployment
  scope: Namespaced
  version: v1alpha1
