apiVersion: fissile.cloudfoundry.org/v1alpha1
kind: BOSHDeployment
metadata:
  name: example-boshdeployment
spec:
  manifest:
    type: "configMap"
    ref: "bosh-manifest"
  ops:
    - type: "configMap"
      ref: "bosh-ops"
    - type: "secret"
      ref: "bosh-ops-secret"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-manifest
data:
  manifest: |
    instance-groups:
      - name: diego
        instances: 3
      - name: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bosh-ops
data:
  ops: |
    - type: replace
      path: /instance-groups/name=diego?/instances
      value: 4

---
apiVersion: v1
kind: Secret
metadata:
  name: bosh-ops-secret
type: Opaque
stringData:
  ops: |
    - type: replace
      path: /instance-groups/name=diego?/instances
      value: 5
