apiVersion: v1
data:
  key1: value1Updated
  key2: value2
kind: ConfigMap
metadata:
  name: example1
---
apiVersion: v1
stringData:
  key1: dmFsdWUx
  key2: dmFsdWUy
kind: Secret
type: Opaque
metadata:
  name: example1
---
apiVersion: quarks.cloudfoundry.org/v1alpha1
kind: QuarksStatefulSet
metadata:
  name: example-quarks-statefulset
spec:
  updateOnConfigChange: true
  template:
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: example-statefulset
      template:
        metadata:
          labels:
            app: example-statefulset
        spec:
          volumes:
          - name: secret1-volume
            secret:
              secretName: example1
          containers:
          - name: busybox
            image: busybox
            command:
            - sleep
            - "3600"
            volumeMounts:
              - name: secret1-volume
                readOnly: true
                mountPath: "/etc/secret1-volume"
            env:
              - name: SPECIAL_KEY
                valueFrom:
                  configMapKeyRef:
                    name: example1
                    key: key1
