apiVersion: v1
name: cf-operator
version: x.x.x
appVersion: x.x.x
description: A Helm chart for cf-operator, the k8s operator for deploying BOSH releases
home: https://github.com/cloudfoundry-incubator/cf-operator
icon: https://cloudfoundry-incubator.github.io/quarks-helm/logo.png
keywords:
- cloudfoundry
- bosh
- quarks
- deployment
sources:
- https://github.com/cloudfoundry-incubator/cf-operator
- https://github.com/cloudfoundry-incubator/quarks-job
- https://github.com/cfcontainerizationbot/cf-operator-base
maintainers:
- name: project-quarks
  email: project-quarks@googlegroups.com
