# Default values for cf-operator.
image:
  repository: cf-operator
  org: cfcontainerization
  tag: foobar
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

nodeSelector: {}

tolerations: []

affinity: {}

rbacEnable: true

serviceAccount:
  cfOperatorServiceAccount:
    create: true
    name:

provider: ""
